"""Rebuild the Omron mobile-base collision geom from its visual meshes.

``omron_mobile_base.xml`` collides the base with a single box,
``pedestal_feet_col``, half-extents 0.35 x 0.25 x 0.19. That box is a tight
AABB of the visual shell -- within 1.4 mm along +/-x and 1.0 mm along +/-y --
but the real base is a *rounded* rectangle, so on the diagonals the box's
square corners stick out ~8 cm past anything that renders. Because the
boundary check calls contact at ``mj_geomDistance(...) <= 0``, an obstacle
approaching a corner trips contact while visibly clear.

MuJoCo collides mesh geoms by their convex hull, so the tightest a *single*
geom can be is the convex hull of the visual shell -- and that hull has, by
construction, exactly the same support function as the visual mesh. It is
therefore exact in every outward direction: zero overshoot, where the box
overshoots by up to 10.7 cm.

The full hull is ~2.9k vertices, which is heavy to collide every step. This
script samples the mesh's support point over `--dirs` evenly spread directions
and hulls those. Every sampled point is a real vertex of the visual mesh, so
the result is *contained* in the true hull: it can never overshoot the visible
shell, and the only error is a sub-millimetre inward deficit on thin
protrusions. That is the conservative direction -- it under-reports rather
than inventing contact.

Writes the mesh next to the visual .obj files and prints a comparison table.

Usage:
    python rebuild_omron_collision.py                # 512 dirs, writes the .obj
    python rebuild_omron_collision.py --dirs 1024
    python rebuild_omron_collision.py --exact        # full hull, zero deficit
    python rebuild_omron_collision.py --dry-run      # report only
"""

import argparse
import glob
import os
import sys

import numpy as np
from scipy.spatial import ConvexHull

def _default_mesh_dir():
    """Locate the shipped Omron meshes via robosuite rather than a relative hop."""
    import robosuite
    root = os.path.dirname(os.path.abspath(robosuite.__path__[0]))
    return os.path.join(root, "robosuite", "models", "assets", "bases",
                        "meshes", "omron_mobile_base")


MESH_DIR = _default_mesh_dir()
OUT_NAME = "omron_base_collision.obj"

# pedestal_feet_col half-extents, straight out of omron_mobile_base.xml
BOX_HALF = np.array([0.35, 0.25, 0.19])


def load_visual_vertices(mesh_dir):
    """Every vertex of omron_0..7.obj, in the wheeled_base frame."""
    v = []
    files = sorted(glob.glob(os.path.join(mesh_dir, "omron_[0-7].obj")))
    if not files:
        raise SystemExit(f"no omron_[0-7].obj under {mesh_dir}")
    for f in files:
        with open(f) as fh:
            for line in fh:
                if line.startswith("v "):
                    v.append([float(x) for x in line.split()[1:4]])
    return np.asarray(v, dtype=np.float64), files


def fibonacci_directions(n):
    """n roughly-equidistant unit vectors on the sphere."""
    i = np.arange(n) + 0.5
    phi = np.arccos(1.0 - 2.0 * i / n)
    theta = np.pi * (1.0 + 5.0 ** 0.5) * i
    return np.c_[np.cos(theta) * np.sin(phi),
                 np.sin(theta) * np.sin(phi),
                 np.cos(phi)]


def build_hull(v, dirs=512, exact=False):
    """Convex hull of the shell, optionally simplified by support sampling."""
    if exact:
        h = ConvexHull(v)
        return v[h.vertices]
    idx = np.unique((v @ fibonacci_directions(dirs).T).argmax(axis=0))
    pts = v[idx]
    h = ConvexHull(pts)
    return pts[h.vertices]


def write_obj(path, verts, name="omron_base_collision"):
    """Write the hull of `verts` as a closed triangle mesh."""
    h = ConvexHull(verts)
    # ConvexHull simplices are not consistently wound; orient each outward
    # against the hull centroid so MuJoCo sees sane normals.
    c = verts.mean(axis=0)
    faces = []
    for s in h.simplices:
        a, b, d = verts[s[0]], verts[s[1]], verts[s[2]]
        if np.dot(np.cross(b - a, d - a), a - c) < 0:
            s = [s[0], s[2], s[1]]
        faces.append(s)
    with open(path, "w") as f:
        f.write(f"# {name}\n")
        f.write("# convex hull of omron_0..7.obj -- generated by "
                "robocasa/validation/rebuild_omron_collision.py\n")
        f.write(f"o {name}\n")
        for p in verts:
            f.write(f"v {p[0]:.6f} {p[1]:.6f} {p[2]:.6f}\n")
        for s in faces:
            f.write(f"f {s[0]+1} {s[1]+1} {s[2]+1}\n")
    return len(verts), len(faces)


def compare(v, hull, n_probe=6000, seed=0):
    """Directional overshoot of box and hull against the visual shell."""
    rng = np.random.default_rng(seed)
    d = rng.normal(size=(n_probe, 3))
    d /= np.linalg.norm(d, axis=1, keepdims=True)
    s_mesh = (v @ d.T).max(axis=0)
    s_box = np.abs(d) @ BOX_HALF
    s_hull = (hull @ d.T).max(axis=0)
    return {
        "box": s_box - s_mesh,
        "hull": s_hull - s_mesh,
    }


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--mesh-dir", default=MESH_DIR)
    p.add_argument("--dirs", type=int, default=512,
                   help="support directions to sample (higher = tighter, heavier)")
    p.add_argument("--exact", action="store_true",
                   help="use the full convex hull; zero deficit, ~2.9k verts")
    p.add_argument("--out", default=None)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    mesh_dir = os.path.normpath(args.mesh_dir)
    v, files = load_visual_vertices(mesh_dir)
    print(f"visual shell: {len(files)} meshes, {len(v)} vertices")
    print(f"  bounds min {np.round(v.min(0), 4)}  max {np.round(v.max(0), 4)}")
    print(f"  box        min {np.round(-BOX_HALF, 4)}  max {np.round(BOX_HALF, 4)}")

    hull = build_hull(v, dirs=args.dirs, exact=args.exact)
    g = compare(v, hull)

    print(f"\nrebuilt collision hull: {len(hull)} vertices "
          f"({'exact' if args.exact else f'{args.dirs} support dirs'})")
    print("\ndirectional error vs the visual shell (+ = sticks out past what "
          "you can see):")
    print(f"  {'':10s} {'max':>12} {'mean':>12} {'p99':>12}")
    for k in ("box", "hull"):
        e = g[k]
        label = "box (old)" if k == "box" else "hull (new)"
        print(f"  {label:10s} {e.max()*100:+9.3f} cm {e.mean()*100:+9.3f} cm "
              f"{np.percentile(e, 99)*100:+9.3f} cm")
    worst = g["hull"].min()
    print(f"\n  hull worst inward deficit: {worst*100:.3f} cm "
          f"(under-reports; never invents contact)")
    print(f"  box  worst outward error:  {g['box'].max()*100:+.3f} cm "
          f"(this is the phantom-contact budget)")

    out = args.out or os.path.join(mesh_dir, OUT_NAME)
    if args.dry_run:
        print(f"\n--dry-run: would write {out}")
        return 0
    nv, nf = write_obj(out, hull)
    print(f"\nwrote {out}\n  {nv} vertices, {nf} triangles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
